apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  selector:
    app: website
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008

