apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: app1 
spec:
  selector:
    app: app1
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008

